version: '3'
services:
  web:
    image: nginx:1.25.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/keys:ro